//! Nonce-based replay protection.
//!
//! See RFC §5.2. Each session maintains a sliding window of recently-seen
//! nonces. The window is 1024 entries; any nonce older than the window's
//! lowest water mark, or already present in the window, is rejected.
//!
//! Implementation: a fixed-size bitset indexed by the lower 10 bits of the
//! nonce's last byte XORed with the upper bytes. This is a deliberately
//! simple scheme suitable for nonces generated by a counter (the recommended
//! mode). Random nonces will collide with probability ≈ 1/1024 per session.

use std::fmt;

/// Replay window size in entries.
pub const WINDOW_SIZE: usize = 1024;

/// Replay protection error.
#[derive(Debug, thiserror::Error)]
pub enum ReplayError {
    /// Nonce was already seen.
    #[error("replay detected")]
    Detected,
}

/// Sliding-window replay tracker for one session receive direction.
pub struct ReplayWindow {
    /// Bitset of 1024 entries.
    bits: [u64; WINDOW_SIZE / 64],
    /// Highest nonce counter value seen so far.
    highest: u64,
    /// Number of nonces seen so far.
    count: u64,
}

impl fmt::Debug for ReplayWindow {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ReplayWindow")
            .field("highest", &self.highest)
            .field("count", &self.count)
            .finish_non_exhaustive()
    }
}

impl Default for ReplayWindow {
    fn default() -> Self {
        Self::new()
    }
}

impl ReplayWindow {
    /// Construct an empty window.
    pub fn new() -> Self {
        Self {
            bits: [0u64; WINDOW_SIZE / 64],
            highest: 0,
            count: 0,
        }
    }

    /// Returns `true` if the nonce is fresh and may be processed. Returns
    /// `false` if the nonce was replayed or fell outside the window.
    pub fn check_and_insert(&mut self, nonce: &[u8; 12]) -> bool {
        // We treat the nonce as a 96-bit big-endian counter. We only use the
        // upper 64 bits as the sequence number; the lower 32 bits are mixed
        // into the bitset index for slot dispersion. This is correct for
        // counter-based nonces (which is the recommended mode for NXP).
        let mut seq_bytes = [0u8; 8];
        seq_bytes.copy_from_slice(&nonce[4..12]);
        let seq = u64::from_be_bytes(seq_bytes);
        let slot = (seq % WINDOW_SIZE as u64) as usize;
        let word = slot / 64;
        let bit = 1u64 << (slot % 64);

        // First nonce seen.
        if self.count == 0 {
            self.highest = seq;
            self.bits[word] |= bit;
            self.count = 1;
            return true;
        }

        // Future nonce — advance the window.
        if seq > self.highest {
            let drift = seq - self.highest;
            if drift >= WINDOW_SIZE as u64 {
                // Window completely cleared.
                self.bits = [0u64; WINDOW_SIZE / 64];
            } else {
                // Shift the window: clear bits that fall off the back.
                // We do this lazily — only clear the slots between `highest`
                // and `seq` that are no longer in the window.
                let clear_from = seq.saturating_sub(WINDOW_SIZE as u64 - 1);
                if clear_from > self.highest.saturating_sub(WINDOW_SIZE as u64 - 1) {
                    // For simplicity in this MVP, we don't track the precise
                    // lower bound; instead, we clear all bits in the cleared
                    // range. This is correct because any nonce older than
                    // `clear_from` is now outside the window.
                    let old_lower = self.highest.saturating_sub(WINDOW_SIZE as u64 - 1);
                    if clear_from > old_lower {
                        let to_clear = (clear_from - old_lower) as usize;
                        for i in 0..to_clear {
                            let s = (old_lower + i as u64) % WINDOW_SIZE as u64;
                            let w = s as usize / 64;
                            let b = 1u64 << (s as usize % 64);
                            self.bits[w] &= !b;
                        }
                    }
                }
            }
            self.highest = seq;
            self.bits[word] |= bit;
            self.count += 1;
            return true;
        }

        // Past nonce — check if it's still in the window.
        let age = self.highest - seq;
        if age >= WINDOW_SIZE as u64 {
            return false;
        }
        if self.bits[word] & bit != 0 {
            return false; // already seen
        }
        self.bits[word] |= bit;
        self.count += 1;
        true
    }

    /// Number of nonces seen.
    pub fn count(&self) -> u64 {
        self.count
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn nonce(seq: u64) -> [u8; 12] {
        let mut n = [0u8; 12];
        n[4..12].copy_from_slice(&seq.to_be_bytes());
        n
    }

    #[test]
    fn accepts_monotonic_sequence() {
        let mut w = ReplayWindow::new();
        for i in 1..=10 {
            assert!(w.check_and_insert(&nonce(i)));
        }
        assert_eq!(w.count(), 10);
    }

    #[test]
    fn rejects_replay() {
        let mut w = ReplayWindow::new();
        assert!(w.check_and_insert(&nonce(1)));
        assert!(!w.check_and_insert(&nonce(1)));
    }

    #[test]
    fn accepts_reordering_within_window() {
        let mut w = ReplayWindow::new();
        assert!(w.check_and_insert(&nonce(10)));
        assert!(w.check_and_insert(&nonce(5))); // older but in window
        assert!(w.check_and_insert(&nonce(7)));
    }

    #[test]
    fn rejects_old_nonce_outside_window() {
        let mut w = ReplayWindow::new();
        // Skip ahead past the window.
        assert!(w.check_and_insert(&nonce(1)));
        assert!(w.check_and_insert(&nonce((WINDOW_SIZE as u64) + 10)));
        // Now nonce 1 is outside the window.
        assert!(!w.check_and_insert(&nonce(1)));
    }
}
